version: "3.9"

services:
  postgres:
    image: postgres:15.4
    container_name: taskflow-postgres
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - taskflow_pg_data:/var/lib/postgresql/data

volumes:
  taskflow_pg_data:
